convert script enhancements

diff --git a/container/convert_email b/container/convert_email
--- a/container/convert_email
+++ b/container/convert_email
@@ -1,42 +1,52 @@
 #!/usr/bin/env bash
 
 usage() {
-  echo "Usage: $0 <input> <output>"
+  echo "Usage: $0 [<input> [<output>]]"
   echo ""
-  echo "  <input> can be a file or a directory"
-  echo "  <output> should be a directory"
+  echo "  <input> can be a file or a directory, default: '/source' directory"
+  echo "  <output> should be a file or a directory, default: same directory as <input>"
   echo ""
-  echo "  if <input> is a directory, all *.msg files in it will be processed"
+  echo "  if <input> is a directory"
+  echo "  then all *.msg files in it will be processed"
+  echo "  and <output> should also be a directory"
   echo "  otherwise <input> should be a msg file"
 }
 
+JAVA_OPTS="-Duser.timezone=${DATE_TIMEZONE:-Europe/Brussels} -Duser.language=${DATE_LANGUAGE:-nl} -Duser.country=${DATE_COUNTRY:-BE}"
+CMD_OPTS="-d -hd -a"
+
+CMD="java ${JAVA_OPTS} -jar /emailconverter/emailconverter.jar ${CMD_OPTS}"
+
 convert_file() {
-  file="$(basename -- "$1")"
-  filename="${file%.*}"
-  java -jar /emailconverter/emailconverter.jar -q -hd -a -o "${TARGET}/${filename}.pdf" "$1"
+  if [ -d "${TARGET}" ]
+  then
+    file="$(basename -- "$1")"
+    tgt="${TARGET}/${file}.pdf"
+  else
+    tgt="${TARGET}"
+    mkdir -p "$(basename -- "${tgt}")"
+  fi
+  echo "Converting $(basename "$1") to ${tgt} ..."
+  ${CMD} -o "${tgt}" "$1"
 }
 
-[ -z "$1" ] && echo -e "ERROR: <input> missing\n" && usage && exit 1
-[ -z "$2" ] && echo -e "ERROR: <output> missing\n" && usage && exit 2
-
-SOURCE="$1"
-TARGET="$2"
-
-[ -d "$TARGET" ] || { echo -e "ERROR: Directory '$TARGET' does not exist\n"; usage; exit 3; }
+SOURCE="${1:-/source}"
 
 if [ -f "$SOURCE" ]
 then
-  echo "Processing $(basename "$SOURCE")"
+  TARGET="${2:-$(dirname "$SOURCE")}"
+  [ -d "$TARGET" ] || { echo -e "ERROR: Directory '$TARGET' does not exist\n"; usage; exit 3; }
   convert_file "$SOURCE"
 elif [ -d "$SOURCE" ]
 then
+  TARGET="${2:-${SOURCE}}"
+  [ -d "$TARGET" ] || { echo -e "ERROR: Directory '$TARGET' does not exist\n"; usage; exit 3; }
   for f in $SOURCE/*.msg
   do
-    echo "Processing $(basename "$f")"
     convert_file "$f"
   done
 else
-  echo -e "ERROR: File '$SOURCE' does not exist or is not a directory of file\n"
+  echo -e "ERROR: '$SOURCE' does not exist or is not a directory or file\n"
   usage
   exit 4
 fi
